### PR TITLE
Writer TAG added for Movies & Episodes

### PR DESCRIPTION
**Pull request by bronnel**

### CODE REVIEW

**Comment by courville** [comment]
Thanks for the contribution. Note that if you are modifying the internal nova databases you need a migration script for `VideoOpenHelper.java` and `ScraperTables.java` (`upgradeTo`) ad increment the version of the db. You can check git history of these files to see how it has been handled in the past.

**Comment by bronnel** [comment]
> Thanks for the contribution. Note that if you are modifying the internal nova databases you need a migration script for `VideoOpenHelper.java` and `ScraperTables.java` (`upgradeTo`) ad increment the version of the db. You can check git history of these files to see how it has been handled in the past.

@courville , Thanks , I came across something like that, can you please elaborate a little on that?

**Comment by courville** [comment]
I have not checked your code yet but if you add columns to the database, it is a structural change that needs to be visible on the db version. Have a look for instance at the versioning of `CREATE_VIDEO_VIEW_VXX` and the dedicated section of `onUpgrade` in `VideoOpenHelper`. You will need to increment `DATABASE_VERSION`.
If you do not do this, an old user i.e. with an old `DATABASE_VERSION` will not have the expected columns in the db for the writer and the query will possibly crash. In the migration you can just fill it blank and ensure that your display handles this as well. I hope this is clear.

**Comment by bronnel** [comment]
@courville , In `ScraperTables.java` I changed the version like this, I also changed `DATABASE_VERSION` to 40,  is this correct ?

from
```
    public static void upgradeTo(SQLiteDatabase db, int toVersion) {
        if (toVersion == 37) {
            log.debug("upgradeTo: " + toVersion);
            db.execSQL("ALTER TABLE " + MOVIE_TABLE_NAME + " ADD COLUMN " + VideoStore.Video.VideoColumns.NOVA_PINNED + " INTEGER DEFAULT (0)");
            db.execSQL("ALTER TABLE " + SHOW_TABLE_NAME + " ADD COLUMN " + VideoStore.Video.VideoColumns.NOVA_PINNED + " INTEGER DEFAULT (0)");
        }
        if (toVersion == 38) {
            log.debug("upgradeTo: " + toVersion);
            db.execSQL("ALTER TABLE " + MOVIE_TABLE_NAME + " ADD COLUMN " + VideoStore.Video.VideoColumns.SCRAPER_C_ID + " INTEGER DEFAULT (-1)");
            db.execSQL(CREATE_MOVIE_COLLECTION_TABLE);
        }
        if (toVersion == 39) {
            log.debug("upgradeTo: " + toVersion);

```

to
```
    public static void upgradeTo(SQLiteDatabase db, int toVersion) {
        if (toVersion == 38) {
            log.debug("upgradeTo: " + toVersion);
            db.execSQL("ALTER TABLE " + MOVIE_TABLE_NAME + " ADD COLUMN " + VideoStore.Video.VideoColumns.NOVA_PINNED + " INTEGER DEFAULT (0)");
            db.execSQL("ALTER TABLE " + SHOW_TABLE_NAME + " ADD COLUMN " + VideoStore.Video.VideoColumns.NOVA_PINNED + " INTEGER DEFAULT (0)");
        }
        if (toVersion == 39) {
            log.debug("upgradeTo: " + toVersion);
            db.execSQL("ALTER TABLE " + MOVIE_TABLE_NAME + " ADD COLUMN " + VideoStore.Video.VideoColumns.SCRAPER_C_ID + " INTEGER DEFAULT (-1)");
            db.execSQL(CREATE_MOVIE_COLLECTION_TABLE);
        }
        if (toVersion == 40) {
            log.debug("upgradeTo: " + toVersion);
```

and in `VideoOpenHelper.java`
from
```
 @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        // create db sets initial version to 10
        // TODO: nova first release is has db version 34, reimport upgrade into create, do not forget mirror action on ScraperTables
        log.debug("onUpgrade: upgrading Database from " + oldVersion + " to " + newVersion);
        if (oldVersion < DATABASE_CREATE_VERSION) {
            log.debug("onUpgrade: upgrade not supported for version " + oldVersion + ", recreating the database.");
            // triggers database deletion
            deleteDatabase();
        }
        if (oldVersion < 37) {
            SQLiteUtils.dropView(db, VIDEO_VIEW_NAME);
			ScraperTables.upgradeTo(db, 37);
			db.execSQL(CREATE_VIDEO_VIEW_V37);
        }
        if (oldVersion < 38) {
            SQLiteUtils.dropView(db, VIDEO_VIEW_NAME);
            ScraperTables.upgradeTo(db, 38);
            db.execSQL(CREATE_VIDEO_VIEW_V38);
        }
        if (oldVersion < 39) {
            // drop triggers first before recreation
            SQLiteUtils.dropTrigger(db, "movie_delete");
            SQLiteUtils.dropTrigger(db, "episode_delete");
            SQLiteUtils.dropTrigger(db, "show_delete");
            ScraperTables.upgradeTo(db, 39);
        }
    }
```

to
```
@Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        // create db sets initial version to 10
        // TODO: nova first release is has db version 34, reimport upgrade into create, do not forget mirror action on ScraperTables
        log.debug("onUpgrade: upgrading Database from " + oldVersion + " to " + newVersion);
        if (oldVersion < DATABASE_CREATE_VERSION) {
            log.debug("onUpgrade: upgrade not supported for version " + oldVersion + ", recreating the database.");
            // triggers database deletion
            deleteDatabase();
        }
        if (oldVersion < 38) {
            SQLiteUtils.dropView(db, VIDEO_VIEW_NAME);
			ScraperTables.upgradeTo(db, 38);
			db.execSQL(CREATE_VIDEO_VIEW_V37);
        }
        if (oldVersion < 39) {
            SQLiteUtils.dropView(db, VIDEO_VIEW_NAME);
            ScraperTables.upgradeTo(db, 39);
            db.execSQL(CREATE_VIDEO_VIEW_V38);
        }
        if (oldVersion < 40) {
            // drop triggers first before recreation
            SQLiteUtils.dropTrigger(db, "movie_delete");
            SQLiteUtils.dropTrigger(db, "episode_delete");
            SQLiteUtils.dropTrigger(db, "show_delete");
            ScraperTables.upgradeTo(db, 40);
        }
    }
```

**Comment by courville** [comment]
For now if you install the pre-release and upgrade to your new version, there are silent crashes in the app e.g. due to missing column `e_writers` that was not created during database upgrade process:
```
E SQLiteLog: (1) table EPISODE has no column named e_writers in "INSERT INTO EPISODE(cover_episode,e_poster_id,number_episode,show_episode,e_directors,season_episode,picture_episode,video_id,e_actors,aired_episode,rating_episo
02-09 14:35:41.410  7941  8430 E SQLiteDatabase: Error inserting cover_episode=/data/user/0/org.courville.nova/app_scraper_posters/2390479562402961l.jpg e_poster_id=600 number_episode=9 show_episode=37 e_directors=John Wells season_episode=1 picture_episode=/data/user/0/org.courville.nova/app_scraper_pictures/0-1238935107l.jpg video_id=1000000971 e_actors=B. J. Harrison (Denise), Gloria Garayua (Penny), Mercedes De La Cruz (Stella), Mike Wasko (Tom), Janet Glassford (Rita), Morgana Wyllie (Nora), Beau de Zwager (Stu), Nels Lennarson (Brett), Xavier de Guzman (Ethan), Anthony Scardera (Cal), Erin Karpluk (Sharlene), Mozhan Marnò (Tara), Hilaria Larriva (Brandi), Steve Bacic (Micah) aired_episode=1633039200000 rating_episode=8.7 e_online_id=2912407 e_writers=Colin McKenna name_episode=Bleu ciel plot_episode=De retour à la case départ, Alex, qui réalise à quel point elle s'est perdue en chemin, tente de trouver un refuge sûr et une bouée de sauvetage juridique. e_imdb_id=tt11337908
02-09 14:35:41.410  7941  8430 E SQLiteDatabase: android.database.sqlite.SQLiteException: table EPISODE has no column named e_writers (code 1 SQLITE_ERROR): , while compiling: INSERT INTO EPISODE(cover_episode,e_poster_id,number_episode,show_episode,e_directors,season_episode,picture_episode,video_id,e_actors,aired_episode,rating_episode,e_online_id,e_writers,name_episode,plot_episode,e_imdb_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
```
You need to do something similar as:
```
            db.execSQL("ALTER TABLE " + SHOW_TABLE_NAME + " ADD COLUMN " + VideoStore.Video.VideoColumns.NOVA_PINNED + " INTEGER DEFAULT (0)");
```

Perhaps it is intended in your PR#21 on MediaLib but I do not have in the PR something related to:
```
if (toVersion == 40) {
            log.debug("upgradeTo: " + toVersion);
```
It is still locked to version 39 for some reasons.

**Comment by bronnel** [comment]
@courville , please check out this [commit](https://github.com/nova-video-player/aos-MediaLib/commit/f370a24767e45524e19ea2f8eb21c3ae9582b651) and see if it resolves the issue. 
I did not face any crashes, but I cleared data of nova/uninstall-reinstalled it.

**Comment by courville** [comment]
Please join me on irc to talk further could be easier to converge towards the final solution that is close.
Idea is not to upgrade any of the master `CREATE_VIDEO_VIEW_V32` and other tables.
Just alter these tables in the final upgradeTo new database version.
This way it will guarantee that all current versions in the field will go though every step of the upgrade process.
Any other way will fail and create crashes on the field.
db upgrade is a touchy topic...

**Comment by bronnel** [comment]
@courville , how to chat with you using IRC ? , I never used it

**Comment by bronnel** [comment]
@courville I didn't hear from you

**Comment by courville** [comment]
Hi, sorry I have been busy. Yes any irc client would do I guess. We are now reachable on liberachat #novavideoplayer channel. You can use the web client first https://web.libera.chat/
I will be online later tonight.

**Review by courville — COMMENTED** [review]
Quick question regarding rounded_edges.xml: shouldn't it belong to Video since it is more UI stuff?

**Comment by bronnel** [comment]
> Quick question regarding rounded_edges.xml: shouldn't it belong to Video since it is more UI stuff?

I guess so

**Comment by courville** [comment]
For some reasons your modifications to `ScraperStore` seems to be missing i.e. `ScraperStore.Movie.WRITERS_FORMATTED` and `ScraperStore.Writer.*`

**Comment by courville** [comment]
I reviewed the code in VideoOpenHelper and ScraperTables and I think it should look like this diffs at the end (encompassing all changes you made) [m.diff.zip](https://github.com/nova-video-player/aos-MediaLib/files/8053356/m.diff.zip).

Note that I removed some views that were not needed in nova on top of your patch that should have been removed long ago.

To be clear the diff provided is on top of current v6 branch and gets all your commits and correct them. I had to do this because I wanted to be sure that I understood all your modifications. It will make it harder for you to merge back I guess.

I can push this to nova if you want referencing your pr and cherry pick the other commits.

**Comment by courville** [comment]
And another comment or wish, let's try to separate all the features per merge requests so that it is easier to merge individually. This will force you to create branches on your fork and move between them. Otherwise in my git cherry-picks I will probably miss some patches and generate a mess.

**Comment by courville** [comment]
A part of your pull request has been already merged and pushed to nova please rebase your branch on latest v6.

**Comment by bronnel** [comment]
@courville thanks, I did your recommended rebase

**Comment by courville** [comment]
Let's try this diff for writers
[m.diff.zip](https://github.com/nova-video-player/aos-MediaLib/files/8054349/m.diff.zip)
.

**Comment by bronnel** [comment]
@courville , I added changes from your diff, huge thanks BTW, and I checked ScraperStore and they are already there these two `ScraperStore.Movie.WRITERS_FORMATTED` and `ScraperStore.Writer.*` , I think it is all good now.

**Comment by courville** [comment]
OK we need to alter the movie/show/episode tables to add the writer column in the upgrade process only.
And no need to create the delete triggers since they have been dropped for speedup.
This is what I propose:
[m.diff.zip](https://github.com/nova-video-player/aos-MediaLib/files/8054504/m.diff.zip)

**Comment by courville** [comment]
All has been merged manually.

**Pull request closed without merging**
